// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: image.sql

package db

import (
	"context"
)

const getAllImages = `-- name: GetAllImages :many
SELECT id, url, spot_id FROM image
`

func (q *Queries) GetAllImages(ctx context.Context) ([]Image, error) {
	rows, err := q.db.Query(ctx, getAllImages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(&i.ID, &i.Url, &i.SpotID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, url, spot_id FROM image WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (Image, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i Image
	err := row.Scan(&i.ID, &i.Url, &i.SpotID)
	return i, err
}

const insertImage = `-- name: InsertImage :one
INSERT INTO image(
    url, spot_id
) VALUES (
             $1, $2
         )RETURNING id, url, spot_id
`

type InsertImageParams struct {
	Url    string
	SpotID int64
}

func (q *Queries) InsertImage(ctx context.Context, arg InsertImageParams) (Image, error) {
	row := q.db.QueryRow(ctx, insertImage, arg.Url, arg.SpotID)
	var i Image
	err := row.Scan(&i.ID, &i.Url, &i.SpotID)
	return i, err
}
