// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: location.sql

package db

import (
	"context"
)

const getAllLocations = `-- name: GetAllLocations :many
SELECT id, address, latitude, longitude FROM location
`

func (q *Queries) GetAllLocations(ctx context.Context) ([]Location, error) {
	rows, err := q.db.Query(ctx, getAllLocations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Location
	for rows.Next() {
		var i Location
		if err := rows.Scan(
			&i.ID,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLocationByID = `-- name: GetLocationByID :one
SELECT id, address, latitude, longitude FROM location WHERE id = $1
`

func (q *Queries) GetLocationByID(ctx context.Context, id int64) (Location, error) {
	row := q.db.QueryRow(ctx, getLocationByID, id)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}

const insertLocation = `-- name: InsertLocation :one
INSERT INTO location(
    address, latitude, longitude
) VALUES (
             $1, $2, $3
         )RETURNING id, address, latitude, longitude
`

type InsertLocationParams struct {
	Address   string
	Latitude  float64
	Longitude float64
}

func (q *Queries) InsertLocation(ctx context.Context, arg InsertLocationParams) (Location, error) {
	row := q.db.QueryRow(ctx, insertLocation, arg.Address, arg.Latitude, arg.Longitude)
	var i Location
	err := row.Scan(
		&i.ID,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
	)
	return i, err
}
