// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SpotCategory string

const (
	SpotCategoryGamta              SpotCategory = "Gamta"
	SpotCategoryLaukoTreniruokliai SpotCategory = "Lauko_treniruokliai"
	SpotCategorySlaptosVietos      SpotCategory = "Slaptos_vietos"
	SpotCategoryRestoranai         SpotCategory = "Restoranai"
	SpotCategoryParduotuves        SpotCategory = "Parduotuves"
)

func (e *SpotCategory) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SpotCategory(s)
	case string:
		*e = SpotCategory(s)
	default:
		return fmt.Errorf("unsupported scan type for SpotCategory: %T", src)
	}
	return nil
}

type NullSpotCategory struct {
	SpotCategory SpotCategory
	Valid        bool // Valid is true if SpotCategory is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSpotCategory) Scan(value interface{}) error {
	if value == nil {
		ns.SpotCategory, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SpotCategory.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSpotCategory) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SpotCategory), nil
}

func (e SpotCategory) Valid() bool {
	switch e {
	case SpotCategoryGamta,
		SpotCategoryLaukoTreniruokliai,
		SpotCategorySlaptosVietos,
		SpotCategoryRestoranai,
		SpotCategoryParduotuves:
		return true
	}
	return false
}

func AllSpotCategoryValues() []SpotCategory {
	return []SpotCategory{
		SpotCategoryGamta,
		SpotCategoryLaukoTreniruokliai,
		SpotCategorySlaptosVietos,
		SpotCategoryRestoranai,
		SpotCategoryParduotuves,
	}
}

type UserRole string

const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin,
		UserRoleUser:
		return true
	}
	return false
}

func AllUserRoleValues() []UserRole {
	return []UserRole{
		UserRoleAdmin,
		UserRoleUser,
	}
}

type Image struct {
	ID     int64
	Url    string
	SpotID int64
}

type Location struct {
	ID        int64
	Address   string
	Latitude  float64
	Longitude float64
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type Spot struct {
	ID          int64
	Category    SpotCategory
	Name        string
	Description string
	LocationID  int64
}

type User struct {
	ID        int64
	Email     string
	Password  string
	Role      UserRole
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
