// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: spot.sql

package db

import (
	"context"
)

const getAllSpots = `-- name: GetAllSpots :many
SELECT id, category, name, description, location_id FROM spot
`

func (q *Queries) GetAllSpots(ctx context.Context) ([]Spot, error) {
	rows, err := q.db.Query(ctx, getAllSpots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Spot
	for rows.Next() {
		var i Spot
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Name,
			&i.Description,
			&i.LocationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicSpotsByCategoryWithDetails = `-- name: GetPublicSpotsByCategoryWithDetails :many
SELECT
    s.id,
    s.name,
    s.category,
    l.address,
    l.latitude,
    l.longitude,
    COALESCE((SELECT url FROM image WHERE spot_id = s.id LIMIT 1), '')::text as image_url
FROM spot s
         INNER JOIN location l ON s.location_id = l.id
WHERE s.category = $1 AND s.category != 'Slaptos_vietos'
ORDER BY s.id
`

type GetPublicSpotsByCategoryWithDetailsRow struct {
	ID        int64
	Name      string
	Category  SpotCategory
	Address   string
	Latitude  float64
	Longitude float64
	ImageUrl  string
}

func (q *Queries) GetPublicSpotsByCategoryWithDetails(ctx context.Context, category SpotCategory) ([]GetPublicSpotsByCategoryWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPublicSpotsByCategoryWithDetails, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicSpotsByCategoryWithDetailsRow
	for rows.Next() {
		var i GetPublicSpotsByCategoryWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPublicSpotsWithDetails = `-- name: GetPublicSpotsWithDetails :many
SELECT
    s.id,
    s.name,
    s.category,
    l.address,
    l.latitude,
    l.longitude,
    COALESCE((SELECT url FROM image WHERE spot_id = s.id LIMIT 1), '')::text as image_url
FROM spot s
         INNER JOIN location l ON s.location_id = l.id
WHERE s.category != 'Slaptos_vietos'
ORDER BY s.id
`

type GetPublicSpotsWithDetailsRow struct {
	ID        int64
	Name      string
	Category  SpotCategory
	Address   string
	Latitude  float64
	Longitude float64
	ImageUrl  string
}

func (q *Queries) GetPublicSpotsWithDetails(ctx context.Context) ([]GetPublicSpotsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getPublicSpotsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPublicSpotsWithDetailsRow
	for rows.Next() {
		var i GetPublicSpotsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotByID = `-- name: GetSpotByID :one
SELECT id, category, name, description, location_id FROM spot WHERE id = $1
`

func (q *Queries) GetSpotByID(ctx context.Context, id int64) (Spot, error) {
	row := q.db.QueryRow(ctx, getSpotByID, id)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.Description,
		&i.LocationID,
	)
	return i, err
}

const getSpotsByCategoryWithDetails = `-- name: GetSpotsByCategoryWithDetails :many
SELECT
    s.id,
    s.name,
    s.category,
    l.address,
    l.latitude,
    l.longitude,
    COALESCE((SELECT url FROM image WHERE spot_id = s.id LIMIT 1), '')::text AS image_url
FROM spot s
         INNER JOIN location l ON s.location_id = l.id
WHERE s.category = $1
ORDER BY s.id
`

type GetSpotsByCategoryWithDetailsRow struct {
	ID        int64
	Name      string
	Category  SpotCategory
	Address   string
	Latitude  float64
	Longitude float64
	ImageUrl  string
}

func (q *Queries) GetSpotsByCategoryWithDetails(ctx context.Context, category SpotCategory) ([]GetSpotsByCategoryWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getSpotsByCategoryWithDetails, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotsByCategoryWithDetailsRow
	for rows.Next() {
		var i GetSpotsByCategoryWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotsWithDetails = `-- name: GetSpotsWithDetails :many
SELECT
    s.id,
    s.name,
    s.category,
    l.address,
    l.latitude,
    l.longitude,
    COALESCE((SELECT url FROM image WHERE spot_id = s.id LIMIT 1), '')::text as image_url
FROM spot s
         INNER JOIN location l ON s.location_id = l.id
ORDER BY s.id
`

type GetSpotsWithDetailsRow struct {
	ID        int64
	Name      string
	Category  SpotCategory
	Address   string
	Latitude  float64
	Longitude float64
	ImageUrl  string
}

func (q *Queries) GetSpotsWithDetails(ctx context.Context) ([]GetSpotsWithDetailsRow, error) {
	rows, err := q.db.Query(ctx, getSpotsWithDetails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotsWithDetailsRow
	for rows.Next() {
		var i GetSpotsWithDetailsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSpot = `-- name: InsertSpot :one
INSERT INTO spot(
    category, name, description, location_id
) VALUES (
             $1, $2, $3, $4
         ) RETURNING id, category, name, description, location_id
`

type InsertSpotParams struct {
	Category    SpotCategory
	Name        string
	Description string
	LocationID  int64
}

func (q *Queries) InsertSpot(ctx context.Context, arg InsertSpotParams) (Spot, error) {
	row := q.db.QueryRow(ctx, insertSpot,
		arg.Category,
		arg.Name,
		arg.Description,
		arg.LocationID,
	)
	var i Spot
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Name,
		&i.Description,
		&i.LocationID,
	)
	return i, err
}
